name: Resharper Code Analysis
 
on: 
    push:
        branches: [master]
 
jobs:
  resharper:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
           dotnet-version: 3.1.301
      - name: Install resharper
        run: dotnet tool install -g JetBrains.ReSharper.GlobalTools
              
      - name: Add packages
        run: dotnet add Alert-To-Care-Tests/Alert-To-Care-Tests.csproj package xunit --version 2.4.0

      - name: Add packages
        run: dotnet add AlertToCare-AutomatedTests/AlertToCare-AutomatedTests.csproj package xunit --version 2.4.0
              
      - name: Add packages
        run: dotnet add AlertToCare/AlertToCare.csproj package Microsoft.EntityFrameworkCore --version 3.1.9
        
      - name: Run resharper inspection
        run: jb inspectcode Alert-To-Care/Alert-To-Care.sln /output=insreport.xml
       
      - name: Run resharper duplicate code check
        run: jb dupfinder Alert-To-Care/Alert-To-Care.sln /output=dupreport.xml
       
      - name: Check Reports
        run: powershell ./resharper.ps1
